### ISSUE TITLE
Button Component Refactoring

### ISSUE THREAD

**Issue by SebastianUrdaneguiBisalaya** [SebastianUrdaneguiBisalaya/App-To-Find-Events#1]
Hi @alexamibco!

I have been testing the Button component in my components and I recommend you to put rem measure instead of view-with padding because the behavior of the component is not smooth if you compare when you use rem measure padding.

I attach the code to improve this behavior.

Before changing:

Focusing only on `px-10[vw] py-[1.5vw]`

```react
export const Button: React.FC<ButtonProps> = ({ text, onClick }) => {
  return (
    <button
      onClick={onClick}
      className="px-[10vw] py-[1.5vw] font-semibold text-white bg-[#761CBC] rounded-[10px] hover:bg-[#0DCDAA] font-poppins"
    >
      {text}
    </button>
  );
};
```

After changing:

Focusing only on `px-4 py-3`

```react
export const Button: React.FC<ButtonProps> = ({ text, onClick }) => {
  return (
    <button
      onClick={onClick}
      className="px-4 p-3 font-semibold text-white bg-[#761CBC] rounded-[10px] hover:bg-[#0DCDAA] font-poppins"
    >
      {text}
    </button>
  );
};
```

You will be able to evaluate and decide which is the best option. 🤓
Tks!

**Comment by alexamibco** [comment]
Fixed.
