### ISSUE TITLE
Category Tag Component

### ISSUE THREAD

**Issue by SebastianUrdaneguiBisalaya** [SebastianUrdaneguiBisalaya/App-To-Find-Events#15]
Hello @alexamibco!

Your component is perfect, but I will apply the following change to improve user experience. If you are okay with that, change the code and try to commit.

Goal: When the user hovers over the label, the background should change to a brighter one.

In fact, you can add dynamic styles in Tailwind, but I recommend the following steps:

1. Create a new object with colors:

```
const categoryColors: Record<string, { normal: string; hover: string }> = {
  Concierto: { normal: "bg-blue-100", hover: "bg-blue-300" },
  Fiesta: { normal: "bg-green-100", hover: "bg-green-300" },
  Teatro: { normal: "bg-red-100", hover: "bg-red-300" },
  Ballet: { normal: "bg-purple-100", hover: "bg-purple-300" },
  Otros: { normal: "bg-yellow-100", hover: "bg-yellow-300" },
};
```

2. Then, create a new constant to get the value in each case.
```
const { normal, hover } = categoryColors[category] || { normal: "bg-gray-300", hover: "bg-gray-300" };
```

3. Finally, you must implement onMouseEnter and onMouseLeave to detect the hover and change the background color.

```
<span className={`inline-block mx-1 px-3 py-1 rounded-lg font-poppins font-normal text-sm cursor-pointer ${normal}`}
      onMouseEnter={(e) => e.currentTarget.classList.replace(normal, hover)}
      onMouseLeave={(e) => e.currentTarget.classList.replace(hover, normal)}>
      {category}
    </span>
```

Pls, evaluate this proposal because I am not sure about the impact of using more JavaScript in your code and I do not know how this might affect performance. But, I think this is not a problem.

**Comment by alexamibco** [comment]
Hello, I just included it, please check my changes in the last PR
